BEGIN;

-- DB-06: السماح باستيراد معرّفات مستقرة للمحتوى المرجعي
ALTER TABLE collections ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE books       ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE chapters    ALTER COLUMN id SET GENERATED BY DEFAULT;

-- DB-08: قيمة افتراضية لمعدل البت
ALTER TABLE recordings ALTER COLUMN bitrate_kbps SET DEFAULT 32;

-- DB-07 (P0): إصلاح انهيار التسجيل — ضمان طول الاسم 2..60 دائماً
CREATE OR REPLACE FUNCTION handle_new_user() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE candidate TEXT;
BEGIN
    candidate := NULLIF(TRIM(COALESCE(NEW.raw_user_meta_data->>'full_name', '')), '');
    IF candidate IS NULL OR char_length(candidate) < 2 THEN
        candidate := NULLIF(TRIM(split_part(COALESCE(NEW.email,''), '@', 1)), '');
    END IF;
    IF candidate IS NULL OR char_length(candidate) < 2 THEN
        candidate := 'طالب-' || LEFT(REPLACE(NEW.id::text, '-', ''), 6);
    END IF;
    INSERT INTO public.profiles (id, display_name, role)
    VALUES (NEW.id, LEFT(candidate, 60), 'student')
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END $$;

-- DB-03: حصر قراءة الملفات الشخصية بالمسجّلين
DROP POLICY IF EXISTS profiles_select_public ON profiles;
CREATE POLICY profiles_select_authenticated ON profiles
    FOR SELECT TO authenticated USING (true);

-- DB-04: حجب مفاتيح الإشراف عن الزوار
DROP POLICY IF EXISTS settings_select_all ON app_settings;
CREATE POLICY settings_select_public_keys ON app_settings
    FOR SELECT TO anon USING (key IN ('upload_enabled'));
CREATE POLICY settings_select_authenticated ON app_settings
    FOR SELECT TO authenticated USING (true);

-- DB-01: تحديث التسجيلات — للمشرف فقط، مع تجميد الحقول غير القابلة للتعديل
CREATE POLICY recordings_update_admin ON recordings
    FOR UPDATE TO authenticated
    USING ((SELECT is_admin()))
    WITH CHECK ((SELECT is_admin()));

-- DB-01: اعتماد التسجيل عبر RPC مع أثر تدقيق
CREATE OR REPLACE FUNCTION verify_recording(p_recording_id UUID, p_verified BOOLEAN)
RETURNS recordings LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE r recordings;
BEGIN
    IF NOT is_admin() THEN RAISE EXCEPTION 'FORBIDDEN' USING ERRCODE='42501'; END IF;
    UPDATE recordings SET is_verified = p_verified,
           verified_by = CASE WHEN p_verified THEN auth.uid() ELSE NULL END,
           updated_at = now()
    WHERE id = p_recording_id RETURNING * INTO r;
    IF r.id IS NULL THEN RAISE EXCEPTION 'NOT_FOUND' USING ERRCODE='P0002'; END IF;
    RETURN r;
END $$;

-- DB-02: صيانة العدادات المُفكَّكة (الإصلاح الأهم)
CREATE OR REPLACE FUNCTION bump_likes_count() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE recordings SET likes_count = likes_count + 1 WHERE id = NEW.recording_id;
    ELSE
        UPDATE recordings SET likes_count = GREATEST(likes_count - 1, 0) WHERE id = OLD.recording_id;
    END IF;
    RETURN NULL;
END $$;
CREATE TRIGGER trg_likes_count AFTER INSERT OR DELETE ON likes
    FOR EACH ROW EXECUTE FUNCTION bump_likes_count();

CREATE OR REPLACE FUNCTION bump_listens_count() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
    UPDATE recordings SET listens_count = listens_count + 1 WHERE id = NEW.recording_id;
    RETURN NULL;
END $$;
CREATE TRIGGER trg_listens_count AFTER INSERT ON recording_listens
    FOR EACH ROW EXECUTE FUNCTION bump_listens_count();

-- DB-11: فهارس ناقصة
CREATE INDEX IF NOT EXISTS idx_reports_reporter        ON reports(reporter_id);
CREATE INDEX IF NOT EXISTS idx_content_reports_hadith  ON content_reports(hadith_id);
CREATE INDEX IF NOT EXISTS idx_recordings_user_created ON recordings(user_id, created_at DESC);

-- DB-09: تجميد سطح annotations حتى الإطلاق
DROP POLICY IF EXISTS annotations_insert_own ON annotations;
DROP POLICY IF EXISTS annotations_update_own ON annotations;
DROP POLICY IF EXISTS annotations_delete_own ON annotations;

COMMIT;
